# Generated by Django 5.1.2 on 2024-11-10 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_following_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', through='account.Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
