# Generated by Django 4.2.16 on 2025-01-12 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("70c0cc7e-bf8c-46bd-8db6-22c4fd477505"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
