# Generated by Django 5.1.2 on 2025-01-14 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('869fec87-5b86-424f-b528-1b6c4e54c9c6'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
