# Generated by Django 5.1.2 on 2025-01-14 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('6a667e84-4474-428f-8f14-25f297914673'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
