# Generated by Django 5.1.2 on 2024-12-09 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('3b1817ae-ff77-4a70-ace0-1a6fa61ef29f'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
