# Generated by Django 5.1.2 on 2025-01-14 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('5e6c1ed8-15c3-4c25-8a5e-2521191ba339'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
