# Generated by Django 5.1.2 on 2024-12-30 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_remove_submission_info_remove_submission_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('7138e709-5750-4076-8a24-8e39870dad74'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
