# Generated by Django 5.1.2 on 2024-12-30 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('62c36002-93ea-42f9-8703-072b6e3a2c6a'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
