# Generated by Django 5.1.2 on 2024-12-30 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('35beed74-37ad-4cf6-8272-c13d70a94236'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
