# Generated by Django 4.2.16 on 2024-12-30 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0007_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("f7a881e7-15a4-40f8-8ba3-f975d440a8b6"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
