# Generated by Django 4.2.16 on 2024-12-30 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0009_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("118b45d7-1e3d-4896-be35-5e283fe773f0"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
