# Generated by Django 4.2.16 on 2024-12-30 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0010_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("0d6dbb0e-bf32-4ace-a7d5-ded90c895449"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
