# Generated by Django 4.2.16 on 2024-12-30 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0011_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("0d5af9c7-0599-4c47-86bc-a55a3d413dae"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
