# Generated by Django 5.1.2 on 2025-01-02 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('0302e365-abe2-465c-b8d5-51986dc25769'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
