# Generated by Django 5.1.2 on 2025-01-02 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('76d73f1a-1402-49b6-afb8-fa77bc85830f'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
