# Generated by Django 5.1.2 on 2025-01-02 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('a1968edd-ac74-4055-89ff-f5efcfa86103'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
