# Generated by Django 4.2.16 on 2024-12-30 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0012_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("c008bd25-b701-4c6b-a8b7-2cb798cb591c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
