# Generated by Django 4.2.16 on 2025-01-02 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0013_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("6da1bc97-2b62-4aee-94bb-b0946b2a5650"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
