# Generated by Django 4.2.16 on 2025-01-03 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0014_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("330f5c6a-cc53-4246-b040-b6d1f366bad7"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
