# Generated by Django 5.1.2 on 2025-01-03 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('6c7876ef-1adc-4396-a3fe-bf95b61ac154'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
