# Generated by Django 4.2.16 on 2025-01-03 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0015_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("c0a48936-48db-4f54-80f8-5c7d1328a3b7"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
