# Generated by Django 5.1.2 on 2025-01-03 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0015_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('b9878fc8-a037-41ec-9c7b-f49aa228d1ba'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_spent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_spent',
            field=models.IntegerField(null=True),
        ),
    ]
