# Generated by Django 4.2.16 on 2025-01-03 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0016_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("89aba9ad-d7e3-44b8-8f7c-8c99c604d82e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="time_spent",
            field=models.IntegerField(null=True),
        ),
    ]
