# Generated by Django 5.1.2 on 2025-01-03 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0016_alter_submission_id_alter_submission_memory_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('894b9aa1-f74b-488b-afac-6a0ff6a7bcee'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
