# Generated by Django 4.2.16 on 2025-01-03 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0017_alter_submission_id_alter_submission_time_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("41918ebf-189d-4b94-910e-9afc2c0e0b54"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="memory_spent",
            field=models.IntegerField(null=True),
        ),
    ]
