# Generated by Django 5.1.2 on 2025-01-11 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('c6756494-9619-4e6e-a82e-01762560da61'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
