# Generated by Django 5.1.2 on 2025-01-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='under_comment_id',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='under_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_comments', to='forum.postcomment'),
        ),
    ]
