# Generated by Django 4.2.16 on 2024-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_postcomment_reply_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(default="", max_length=100),
        ),
    ]
