# Generated by Django 5.1.2 on 2024-12-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_tags'),
        ('problem', '0011_remove_tag_type_tag_parent_delete_tagtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='check_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='problem.tag'),
        ),
    ]
