# Generated by Django 4.2.16 on 2024-12-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0004_remove_post_tags_alter_postcomment_check_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="under_comment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="under_comments",
                to="forum.postcomment",
            ),
        ),
    ]
