# Generated by Django 5.1.2 on 2024-12-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_tags_alter_postcomment_check_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='under_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='forum.postcomment'),
        ),
    ]
