# Generated by Django 5.1.2 on 2025-01-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_postcomment_under_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='check_status',
            field=models.BooleanField(default=True),
        ),
    ]
