# Generated by Django 5.1.2 on 2025-01-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='problem_status',
        ),
    ]
