# Generated by Django 5.1.2 on 2024-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_pass_users_alter_problem_star_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
