# Generated by Django 5.1.2 on 2024-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_solution_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlist',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
