# Generated by Django 5.1.2 on 2024-12-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problemlist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='hint',
            new_name='data_range',
        ),
    ]
