# Generated by Django 5.1.2 on 2024-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_rename_hint_problem_data_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
