# Generated by Django 5.1.2 on 2024-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_solution_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='like_count',
            field=models.IntegerField(),
        ),
    ]
