# Generated by Django 5.1.2 on 2024-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_alter_solution_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.TextField(),
        ),
    ]
