# Generated by Django 5.1.2 on 2024-12-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_alter_solution_like_count_alter_solution_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='last_update_time',
        ),
    ]
