# Generated by Django 5.1.2 on 2024-12-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_remove_solution_last_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='problem.tag'),
        ),
        migrations.DeleteModel(
            name='TagType',
        ),
    ]
