# Generated by Django 5.1.2 on 2024-12-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_remove_tag_type_tag_parent_delete_tagtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemlist',
            name='difficulty',
        ),
    ]
