# Generated by Django 5.1.2 on 2024-12-17 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_remove_problemlist_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioncomment',
            name='reply_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_comment_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
