# Generated by Django 5.1.2 on 2024-12-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_solutioncomment_reply_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_case_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
