# Generated by Django 5.1.2 on 2025-01-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='attempt_cnt',
            new_name='attempt_count',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='pass_cnt',
            new_name='pass_count',
        ),
    ]
