# Generated by Django 5.1.2 on 2025-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_alter_problem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='attempt_cnt',
            new_name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='pass_cnt',
        ),
        migrations.AddField(
            model_name='problem',
            name='pass_count',
            field=models.IntegerField(default=0),
        ),
    ]
